### ISSUE TITLE
rename repo to cleaver

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Cleaver#118]
this requires archiving the old version first.

**Comment by jcfr** [comment]
* [x] Repository renamed from `Cleaver` to `Cleaver1`
* [x] Repository renamed from `Cleaver2` to `Cleaver`

This `Cleaver1` repository was related to the development of Cleaver 1.x and became obsolete in mid 2014 when the development of Cleaver 2.x started.

The table describes the renaming of the Cleaver 1 and Cleaver 2 GitHub repositories:


|             | From July 2013 to April 2023 | Since April 2023        |
|-------------|------------------------------|-------------------------|
| Cleaver 1.x | `SCIInstitute/Cleaver`       | `SCIInstitute/Cleaver1` |
| Cleaver 2.x | `SCIInstitute/Cleaver2`      | `SCIInstitute/Cleaver`  |

Related pull requests:
* https://github.com/SCIInstitute/cleaver.pages/pull/5
* https://github.com/SCIInstitute/Cleaver1/pull/11
